import {writable} from 'svelte/store';
let subject = {
  SF210 : {name : 'SF210', 
           sec1 : 'Section 760001',
           sec2 : 'Section 760002', 
           sj   : '[ SF210 : Programming Skill Development 1 ]',
           prof : 'Assoc. Prof. Dr. Weerachai Anotaipaiboon',
           day : 'Tue' ,
           time1 : '09.30 - 12.30',
           time2 : '13.30 - 16.30',
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student1 : '1', 
           num_student2 : '21',
           max_student : '30'},
  SF210_2 : {name : 'SF210',
            sec2 : 'Section 760002'
            },
  
  SF220 : {name : 'SF220', 
           sec : 'Section 760001', 
           sj   : '[ SF220 : Introduction to Software Engineering ]',
           prof : 'Assoc. Prof. Dr. Weerachai Anotaipaiboon',
           day : 'Mon', 
           time : '09.30 - 12.30', 
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student : '0', 
           max_student : '77'},
 
  SF230 : {name : 'SF230', 
           sec : 'Section 760001', 
           sj   : '[ SF230 : Linear Algebra and Numerical Methods ]', 
           prof : 'Assoc. Prof. Dr. Weerachai Anotaipaiboon',
           day : 'Wed', 
           time : '13.30 - 16.30', 
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student : '23', 
           max_student : '86'},
  
  TU107 : {name : 'TU107', 
           sec : 'Section 760001', 
           sj : '[ TU107 : Digital Skill and Problem Solving ]', 
           prof : 'Assoc. Prof. Dr. Weerachai Anotaipaiboon',
           day : 'Thu', 
           time : '13.30 - 16.30', 
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student : '17', 
           max_student : '63'},
  
  TU109 : {name : 'TU109', 
           sec : 'Section 760001', 
           sj : '[ TU109 : Innovation and Entrepreneurial Mindset ]', 
           prof : 'T. Thanapath Cheeranawanith',
           day : 'Thu', 
           time : '09.30 - 12.30', 
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student : '19', 
           max_student : '63'},

  TU105 : {name : 'TU105',
           sec : 'Section 760001',
           sj : '[ TU105 : Communication Skills in English ]',
           prof : 'T. Kriengkrai Sakulprasertsri',
           day : 'Thu',
           time : '09.30 - 12.30', 
           credit : '3', 
           cost : '5,400 BAHT', 
           num_student : '19', 
           max_student : '26'},

  TU050 : {name : 'TU050',
           sec : 'Section 760001',
           sj : '[ TU050 : English Skills Development ]',
           prof : 'T. Wipakorn Chayopong Kawasaki',
           day : 'Thu',
           time : '09.30 - 12.30',
           credit : '3',
           cost : '5,400 BAHT',
           num_student : '24',
           max_student : '30'},
  
  MA111 : {name : 'MA111',
           sec : 'Section 760001', 
           sj :'[ MA111 : Fundamentals Of Calculus ]',
           prof : 'T. Supakun Panasawatwong',
           day : 'Tue and Thu',
           time : '08.00 - 09.30',
           credit : '3',
           cost : '5,400 BAHT',
           num_student : '75',
           max_student : '80'},
  
  TU104 : {name : 'TU104',
           sec : 'Section 760001',
           sj : '[ TU104 : Critical Thinking Reading and Writing ]',
           prof : 'T. Warangkana Srikamnerd',
           day : 'Mon',
           time : '09.30 - 12.30',
           credit : '3',
           cost : '5,400 BAHT',
           num_student : '22',
           max_student : '30'},
  
  SC135 : {name : 'SC135',
           sec  : 'Section 760001',
           sj   : '[ SC135 : General Physics]',
           prof : 'T. Akkawat Ruammaitree',
           day  : 'Thu',
           time : '13.30 - 16.30',
           credit : '3',
           cost : '5,400 BAHT',
           num_student : '69',
           max_student : '80'},
  
  CN311 : {name : 'CN311',
           sec  : 'Section 760001',
           sj   : '[ CN311 : Operating Systems]',
           prof : 'Asst. Prof. Dr. Supakit Prueksaaroon',
           day  : 'Fri',
           time : '13.30 - 16.30',
           credit : '3',
           cost : '5,400 BAHT',
           num_student : '1',
           max_student : '60'}
}

let select_subject = []

export const vicha = writable(subject);
export const list_subject = writable(select_subject);
